// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ProjectOverview.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Verify Branches & Projects link exists
        /// </summary>
        public void BranchesandProjectsLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIBranchesProjectsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument3.UITopPane.UIBranchesProjectsHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Branches & Projects' link equals 'Branches & Projects'
            Assert.AreEqual(this.BranchesandProjectsLinkExpectedValues.UIBranchesProjectsHyperlinkInnerText, uIBranchesProjectsHyperlink.InnerText, "No Branches & Projects link available");
        }
        
        /// <summary>
        /// Close browser window by clicking (X)
        /// </summary>
        public void CloseBrowser()
        {
            #region Variable Declarations
            BrowserWindow uINewtabInternetExplorWindow = this.UINewtabInternetExplorWindow;
            #endregion

            // Perform Close on Browser Window
            uINewtabInternetExplorWindow.Close();
        }
        
        /// <summary>
        /// Verify the Programs Link in the content menu exists
        /// </summary>
        public void ContentMenu_ProgramsLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIProgramsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument1.UICbpspmenus1Custom.UIProgramsHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Programs' link equals 'Programs'
            Assert.AreEqual(this.ContentMenu_ProgramsLinkExpectedValues.UIProgramsHyperlinkInnerText, uIProgramsHyperlink.InnerText, "No Programs Link in content menu");
        }
        
        /// <summary>
        /// Verify Content Menu button exists
        /// </summary>
        public void ContentMenuButton()
        {
            #region Variable Declarations
            HtmlButton uITogglenavigationButton = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument.UITogglenavigationButton;
            #endregion

            // Verify that the 'ControlType' property of 'Toggle navigation' button equals 'Button'
            Assert.AreEqual(this.ContentMenuButtonExpectedValues.UITogglenavigationButtonControlType, uITogglenavigationButton.ControlType.ToString(), "No Content Menu button");
        }
        
        /// <summary>
        /// Verify individual program link for Fulbright English Teaching Assistant Program (ETA) exists in Programs list
        /// </summary>
        public void IndividualProgramLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIFulbrightEnglishTeacHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument2.UITopPane.UIFulbrightEnglishTeacHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Fulbright English Teaching Assistant Program (ETA)' link equals 'Fulbright English Teaching Assistant Program (ETA)'
            Assert.AreEqual(this.IndividualProgramLinkExpectedValues.UIFulbrightEnglishTeacHyperlinkInnerText, uIFulbrightEnglishTeacHyperlink.InnerText, "No Fulbright English Teaching Assistant Program (ETA) link available");
        }
        
        /// <summary>
        /// Verify the individual project link for Fulbright ETA Armenia 2014 exists for selection.
        /// </summary>
        public void IndividualProjectLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIFulbrightETAArmenia2Hyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument5.UISortlistPane.UIFulbrightETAArmenia2Hyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Fulbright ETA Armenia 2014' link equals 'Fulbright ETA Armenia 2014'
            Assert.AreEqual(this.IndividualProjectLinkExpectedValues.UIFulbrightETAArmenia2HyperlinkInnerText, uIFulbrightETAArmenia2Hyperlink.InnerText, "No Fulbright ETA Armenia 2014 project link available.");
        }
        
        /// <summary>
        /// Open browser; navigate to QA page; login with ECATest creds; click sign in
        /// </summary>
        public void LogintoQA()
        {
            #region Variable Declarations
            WinEdit uIAddressandsearchusinEdit = this.UINewtabInternetExplorWindow.UIAddressBarClient.UIAddressandsearchusinEdit;
            WinEdit uIItemEdit = this.UINewtabInternetExplorWindow.UIItemWindow.UIItemEdit;
            WinButton uIGotohttpsecakmtqaazuButton = this.UINewtabInternetExplorWindow.UIPageControlToolBar.UIGotohttpsecakmtqaazuButton;
            HtmlEdit uIUseraccountEdit = this.UINewtabInternetExplorWindow.UISignintoAzureActiveDDocument.UIUseraccountEdit;
            HtmlEdit uIPasswordEdit = this.UINewtabInternetExplorWindow.UISignintoAzureActiveDDocument.UIPasswordEdit;
            HtmlSpan uISigninPane = this.UINewtabInternetExplorWindow.UISignintoAzureActiveDDocument.UISigninPane;
            #endregion

            // Go to web page 'about:Tabs' using new browser instance
            this.UINewtabInternetExplorWindow.LaunchUrl(new System.Uri(this.LogintoQAParams.UINewtabInternetExplorWindowUrl));

            // Click 'Address and search using Google' text box
            Mouse.Click(uIAddressandsearchusinEdit, new Point(29, 9));

            // Type 'https://eca-kmt-qa.azurewebsites.net/' in text box
            Keyboard.SendKeys(uIItemEdit, this.LogintoQAParams.UIItemEditSendKeys, ModifierKeys.None);

            // Click 'Go to “https://eca-kmt-qa.azurewebsites.net/” (Alt...' button
            Mouse.Click(uIGotohttpsecakmtqaazuButton, new Point(10, 9));

            // Type 'ECATest1@statedept.us' in 'User account' text box
            uIUseraccountEdit.Text = this.LogintoQAParams.UIUseraccountEditText;

            // Type '********' in 'Password' text box
            uIPasswordEdit.Password = this.LogintoQAParams.UIPasswordEditPassword;

            // Double-Click 'Sign in' pane
            Mouse.DoubleClick(uISigninPane, new Point(28, 12));
        }
        
        /// <summary>
        /// Verify the Projects Overview section displays for the individual project's overview (Fulbright ETA Armenia 2014)
        /// </summary>
        public void ProjectsOverviewSection()
        {
            #region Variable Declarations
            HtmlDiv uIOverviewEnglishlanguPane = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument6.UITopPane.UIOverviewEnglishlanguPane;
            #endregion

            // Verify that the 'InnerText' property of 'Overview English language teac' pane contains 'Overview
            //
            //	
            //
            //
            //English language teaching assistant program for Armenia 2014
            // 
            // 
            //
            //
            //Details
            //
            //
            //
            //Themes
            //
            //
            // 
            //
            //Strategic Goals
            //
            //  
            //
            //
            //Focus
            // 
            //language learning
            //
            //
            //Office
            //
            //Office of the Executive Director
            //
            //
            //Program
            //
            //Fulbright English Teaching Assistant Program (ETA)
            //
            //
            // of Contact
            //
            // 
            //
            //Snapshot
            //
            //
            //
            //
            //Locations
            //
            //
            //
            // '
            StringAssert.Contains(uIOverviewEnglishlanguPane.InnerText, this.ProjectsOverviewSectionExpectedValues.UIOverviewEnglishlanguPaneInnerText, "No Projects Overview section available.");
        }
        
        /// <summary>
        /// Refresh/reload All Programs page for display
        /// </summary>
        public void RefreshAllProgramsPage()
        {
            #region Variable Declarations
            HtmlHyperlink uIProgramsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument2.UICbpspmenus1Custom.UIProgramsHyperlink;
            #endregion

            // Type '{F5}' in 'Programs' link
            Keyboard.SendKeys(uIProgramsHyperlink, this.RefreshAllProgramsPageParams.UIProgramsHyperlinkSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Refresh/reload Branches & Projects page for display of Projects list
        /// </summary>
        public void RefreshBranchesandProjectsPage()
        {
            #region Variable Declarations
            HtmlHyperlink uIBranchesProjectsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument4.UITopPane.UIBranchesProjectsHyperlink;
            #endregion

            // Type '{F5}' in 'Branches & Projects' link
            Keyboard.SendKeys(uIBranchesProjectsHyperlink, this.RefreshBranchesandProjectsPageParams.UIBranchesProjectsHyperlinkSendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Refresh/Reload individual Program Page for display
        /// </summary>
        public void RefreshIndividualProgramPage()
        {
            #region Variable Declarations
            HtmlDocument uIHttpsecakmtqaazureweDocument3 = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument3;
            #endregion

            // Type '{F5}' in 'https://eca-kmt-qa.azurewebsites.net/#/offices/1/p...' document
            Keyboard.SendKeys(uIHttpsecakmtqaazureweDocument3, this.RefreshIndividualProgramPageParams.UIHttpsecakmtqaazureweDocument3SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Refresh/Reload Project Overview Page to display the Project Overview for the selected project (Fulbright ETA Armenia 2014)
        /// </summary>
        public void RefreshProjectOverviewPage()
        {
            #region Variable Declarations
            HtmlDocument uIHttpsecakmtqaazureweDocument6 = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument6;
            #endregion

            // Type '{F5}' in 'https://eca-kmt-qa.azurewebsites.net/#/offices/1/p...' document
            Keyboard.SendKeys(uIHttpsecakmtqaazureweDocument6, this.RefreshProjectOverviewPageParams.UIHttpsecakmtqaazureweDocument6SendKeys, ModifierKeys.None);
        }
        
        /// <summary>
        /// Scroll Down All Programs Page to locate individual program for selection.
        /// </summary>
        public void ScrollDownAllPrograms()
        {
            #region Variable Declarations
            HtmlDocument uIHttpsecakmtqaazureweDocument2 = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument2;
            #endregion

            // Double-Click 'https://eca-kmt-qa.azurewebsites.net/#/allprograms...' document
            Mouse.DoubleClick(uIHttpsecakmtqaazureweDocument2, new Point(1360, 653));

            // Click 'https://eca-kmt-qa.azurewebsites.net/#/allprograms...' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument2, new Point(1360, 653));

            // Click 'https://eca-kmt-qa.azurewebsites.net/#/allprograms...' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument2, new Point(1360, 653));

            // Click 'https://eca-kmt-qa.azurewebsites.net/#/allprograms...' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument2, new Point(1360, 653));

            // Click 'https://eca-kmt-qa.azurewebsites.net/#/allprograms...' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument2, new Point(1360, 653));
        }
        
        /// <summary>
        /// Scroll down to view the Projects List on the Branches & Projects page.
        /// </summary>
        public void ScrollDownBranchesandProjects()
        {
            #region Variable Declarations
            HtmlDocument uIHttpsecakmtqaazureweDocument5 = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument5;
            #endregion

            // Click 'https://eca-kmt-qa.azurewebsites.net/' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument5, new Point(1357, 651));

            // Click 'https://eca-kmt-qa.azurewebsites.net/' document
            Mouse.Click(uIHttpsecakmtqaazureweDocument5, new Point(1357, 651));
        }
        
        /// <summary>
        /// Click the link for Branches & Projects to bring up the project list for the program.
        /// </summary>
        public void SelectBranchesandProjectsLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIBranchesProjectsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument3.UITopPane.UIBranchesProjectsHyperlink;
            #endregion

            // Click 'Branches & Projects' link
            Mouse.Click(uIBranchesProjectsHyperlink, new Point(61, 5));
        }
        
        /// <summary>
        /// Toggle/Click the Content Menu button to expand the content menu
        /// </summary>
        public void SelectContentMenuButton()
        {
            #region Variable Declarations
            HtmlSpan uIItemPane = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument1.UIItemPane;
            #endregion

            // Click pane
            Mouse.Click(uIItemPane, new Point(14, 1));
        }
        
        /// <summary>
        /// Click the link for the individual program for Fulbright English Teaching Assistant Program (ETA)
        /// </summary>
        public void SelectIndividualProgram()
        {
            #region Variable Declarations
            HtmlHyperlink uIFulbrightEnglishTeacHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument2.UITopPane.UIFulbrightEnglishTeacHyperlink;
            #endregion

            // Click 'Fulbright English Teaching Assistant Program (ETA)' link
            Mouse.Click(uIFulbrightEnglishTeacHyperlink, new Point(217, 12));
        }
        
        /// <summary>
        /// Click on the link for the individual project from the projects list to display the project overview. (Fulbright ETA Armenia 2014)
        /// </summary>
        public void SelectIndividualProject()
        {
            #region Variable Declarations
            HtmlHyperlink uIFulbrightETAArmenia2Hyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument5.UISortlistPane.UIFulbrightETAArmenia2Hyperlink;
            #endregion

            // Click 'Fulbright ETA Armenia 2014' link
            Mouse.Click(uIFulbrightETAArmenia2Hyperlink, new Point(85, 11));
        }
        
        /// <summary>
        /// Click the Programs Link to navigate to All Programs Page
        /// </summary>
        public void SelectProgramsLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIProgramsHyperlink = this.UINewtabInternetExplorWindow.UIHttpsecakmtqaazureweDocument1.UICbpspmenus1Custom.UIProgramsHyperlink;
            #endregion

            // Click 'Programs' link
            Mouse.Click(uIProgramsHyperlink, new Point(66, 32));
        }
        
        #region Properties
        public virtual BranchesandProjectsLinkExpectedValues BranchesandProjectsLinkExpectedValues
        {
            get
            {
                if ((this.mBranchesandProjectsLinkExpectedValues == null))
                {
                    this.mBranchesandProjectsLinkExpectedValues = new BranchesandProjectsLinkExpectedValues();
                }
                return this.mBranchesandProjectsLinkExpectedValues;
            }
        }
        
        public virtual ContentMenu_ProgramsLinkExpectedValues ContentMenu_ProgramsLinkExpectedValues
        {
            get
            {
                if ((this.mContentMenu_ProgramsLinkExpectedValues == null))
                {
                    this.mContentMenu_ProgramsLinkExpectedValues = new ContentMenu_ProgramsLinkExpectedValues();
                }
                return this.mContentMenu_ProgramsLinkExpectedValues;
            }
        }
        
        public virtual ContentMenuButtonExpectedValues ContentMenuButtonExpectedValues
        {
            get
            {
                if ((this.mContentMenuButtonExpectedValues == null))
                {
                    this.mContentMenuButtonExpectedValues = new ContentMenuButtonExpectedValues();
                }
                return this.mContentMenuButtonExpectedValues;
            }
        }
        
        public virtual IndividualProgramLinkExpectedValues IndividualProgramLinkExpectedValues
        {
            get
            {
                if ((this.mIndividualProgramLinkExpectedValues == null))
                {
                    this.mIndividualProgramLinkExpectedValues = new IndividualProgramLinkExpectedValues();
                }
                return this.mIndividualProgramLinkExpectedValues;
            }
        }
        
        public virtual IndividualProjectLinkExpectedValues IndividualProjectLinkExpectedValues
        {
            get
            {
                if ((this.mIndividualProjectLinkExpectedValues == null))
                {
                    this.mIndividualProjectLinkExpectedValues = new IndividualProjectLinkExpectedValues();
                }
                return this.mIndividualProjectLinkExpectedValues;
            }
        }
        
        public virtual LogintoQAParams LogintoQAParams
        {
            get
            {
                if ((this.mLogintoQAParams == null))
                {
                    this.mLogintoQAParams = new LogintoQAParams();
                }
                return this.mLogintoQAParams;
            }
        }
        
        public virtual ProjectsOverviewSectionExpectedValues ProjectsOverviewSectionExpectedValues
        {
            get
            {
                if ((this.mProjectsOverviewSectionExpectedValues == null))
                {
                    this.mProjectsOverviewSectionExpectedValues = new ProjectsOverviewSectionExpectedValues();
                }
                return this.mProjectsOverviewSectionExpectedValues;
            }
        }
        
        public virtual RefreshAllProgramsPageParams RefreshAllProgramsPageParams
        {
            get
            {
                if ((this.mRefreshAllProgramsPageParams == null))
                {
                    this.mRefreshAllProgramsPageParams = new RefreshAllProgramsPageParams();
                }
                return this.mRefreshAllProgramsPageParams;
            }
        }
        
        public virtual RefreshBranchesandProjectsPageParams RefreshBranchesandProjectsPageParams
        {
            get
            {
                if ((this.mRefreshBranchesandProjectsPageParams == null))
                {
                    this.mRefreshBranchesandProjectsPageParams = new RefreshBranchesandProjectsPageParams();
                }
                return this.mRefreshBranchesandProjectsPageParams;
            }
        }
        
        public virtual RefreshIndividualProgramPageParams RefreshIndividualProgramPageParams
        {
            get
            {
                if ((this.mRefreshIndividualProgramPageParams == null))
                {
                    this.mRefreshIndividualProgramPageParams = new RefreshIndividualProgramPageParams();
                }
                return this.mRefreshIndividualProgramPageParams;
            }
        }
        
        public virtual RefreshProjectOverviewPageParams RefreshProjectOverviewPageParams
        {
            get
            {
                if ((this.mRefreshProjectOverviewPageParams == null))
                {
                    this.mRefreshProjectOverviewPageParams = new RefreshProjectOverviewPageParams();
                }
                return this.mRefreshProjectOverviewPageParams;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        #endregion
        
        #region Fields
        private BranchesandProjectsLinkExpectedValues mBranchesandProjectsLinkExpectedValues;
        
        private ContentMenu_ProgramsLinkExpectedValues mContentMenu_ProgramsLinkExpectedValues;
        
        private ContentMenuButtonExpectedValues mContentMenuButtonExpectedValues;
        
        private IndividualProgramLinkExpectedValues mIndividualProgramLinkExpectedValues;
        
        private IndividualProjectLinkExpectedValues mIndividualProjectLinkExpectedValues;
        
        private LogintoQAParams mLogintoQAParams;
        
        private ProjectsOverviewSectionExpectedValues mProjectsOverviewSectionExpectedValues;
        
        private RefreshAllProgramsPageParams mRefreshAllProgramsPageParams;
        
        private RefreshBranchesandProjectsPageParams mRefreshBranchesandProjectsPageParams;
        
        private RefreshIndividualProgramPageParams mRefreshIndividualProgramPageParams;
        
        private RefreshProjectOverviewPageParams mRefreshProjectOverviewPageParams;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'BranchesandProjectsLink'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class BranchesandProjectsLinkExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Branches & Projects' link equals 'Branches & Projects'
        /// </summary>
        public string UIBranchesProjectsHyperlinkInnerText = "Branches & Projects";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ContentMenu_ProgramsLink'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class ContentMenu_ProgramsLinkExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Programs' link equals 'Programs'
        /// </summary>
        public string UIProgramsHyperlinkInnerText = "Programs";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ContentMenuButton'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class ContentMenuButtonExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlType' property of 'Toggle navigation' button equals 'Button'
        /// </summary>
        public string UITogglenavigationButtonControlType = "Button";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IndividualProgramLink'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class IndividualProgramLinkExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Fulbright English Teaching Assistant Program (ETA)' link equals 'Fulbright English Teaching Assistant Program (ETA)'
        /// </summary>
        public string UIFulbrightEnglishTeacHyperlinkInnerText = "Fulbright English Teaching Assistant Program (ETA)";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IndividualProjectLink'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class IndividualProjectLinkExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Fulbright ETA Armenia 2014' link equals 'Fulbright ETA Armenia 2014'
        /// </summary>
        public string UIFulbrightETAArmenia2HyperlinkInnerText = "Fulbright ETA Armenia 2014";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'LogintoQA'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class LogintoQAParams
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'about:Tabs' using new browser instance
        /// </summary>
        public string UINewtabInternetExplorWindowUrl = "about:Tabs";
        
        /// <summary>
        /// Type 'https://eca-kmt-qa.azurewebsites.net/' in text box
        /// </summary>
        public string UIItemEditSendKeys = "https://eca-kmt-qa.azurewebsites.net/";
        
        /// <summary>
        /// Type 'ECATest1@statedept.us' in 'User account' text box
        /// </summary>
        public string UIUseraccountEditText = "ECATest1@statedept.us";
        
        /// <summary>
        /// Type '********' in 'Password' text box
        /// </summary>
        public string UIPasswordEditPassword = "pnl8gvcmh7nq2IDxDyIPucvLUfiP5WCkCWyYApPZam4=";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'ProjectsOverviewSection'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class ProjectsOverviewSectionExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Overview English language teac' pane contains 'Overview
        ///
        ///	
        ///
        ///
        ///English language teaching assistant program for Armenia 2014
        /// 
        /// 
        ///
        ///
        ///Details
        ///
        ///
        ///
        ///Themes
        ///
        ///
        /// 
        ///
        ///Strategic Goals
        ///
        ///  
        ///
        ///
        ///Focus
        /// 
        ///language learning
        ///
        ///
        ///Office
        ///
        ///Office of the Executive Director
        ///
        ///
        ///Program
        ///
        ///Fulbright English Teaching Assistant Program (ETA)
        ///
        ///
        /// of Contact
        ///
        /// 
        ///
        ///Snapshot
        ///
        ///
        ///
        ///
        ///Locations
        ///
        ///
        ///
        /// '
        /// </summary>
        public string UIOverviewEnglishlanguPaneInnerText = @"Overview

	


English language teaching assistant program for Armenia 2014
 
 


Details



Themes


 

Strategic Goals

  


Focus
 
language learning


Office

Office of the Executive Director


Program

Fulbright English Teaching Assistant Program (ETA)


 of Contact

 

Snapshot




Locations



 ";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RefreshAllProgramsPage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RefreshAllProgramsPageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{F5}' in 'Programs' link
        /// </summary>
        public string UIProgramsHyperlinkSendKeys = "{F5}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RefreshBranchesandProjectsPage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RefreshBranchesandProjectsPageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{F5}' in 'Branches & Projects' link
        /// </summary>
        public string UIBranchesProjectsHyperlinkSendKeys = "{F5}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RefreshIndividualProgramPage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RefreshIndividualProgramPageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{F5}' in 'https://eca-kmt-qa.azurewebsites.net/#/offices/1/p...' document
        /// </summary>
        public string UIHttpsecakmtqaazureweDocument3SendKeys = "{F5}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RefreshProjectOverviewPage'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class RefreshProjectOverviewPageParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{F5}' in 'https://eca-kmt-qa.azurewebsites.net/#/offices/1/p...' document
        /// </summary>
        public string UIHttpsecakmtqaazureweDocument6SendKeys = "{F5}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Sign in to Azure Active Directory");
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIAddressBarClient UIAddressBarClient
        {
            get
            {
                if ((this.mUIAddressBarClient == null))
                {
                    this.mUIAddressBarClient = new UIAddressBarClient(this);
                }
                return this.mUIAddressBarClient;
            }
        }
        
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIPageControlToolBar UIPageControlToolBar
        {
            get
            {
                if ((this.mUIPageControlToolBar == null))
                {
                    this.mUIPageControlToolBar = new UIPageControlToolBar(this);
                }
                return this.mUIPageControlToolBar;
            }
        }
        
        public UISignintoAzureActiveDDocument UISignintoAzureActiveDDocument
        {
            get
            {
                if ((this.mUISignintoAzureActiveDDocument == null))
                {
                    this.mUISignintoAzureActiveDDocument = new UISignintoAzureActiveDDocument(this);
                }
                return this.mUISignintoAzureActiveDDocument;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument UIHttpsecakmtqaazureweDocument
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument = new UIHttpsecakmtqaazureweDocument(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument1 UIHttpsecakmtqaazureweDocument1
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument1 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument1 = new UIHttpsecakmtqaazureweDocument1(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument1;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument2 UIHttpsecakmtqaazureweDocument2
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument2 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument2 = new UIHttpsecakmtqaazureweDocument2(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument2;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument3 UIHttpsecakmtqaazureweDocument3
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument3 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument3 = new UIHttpsecakmtqaazureweDocument3(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument3;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument4 UIHttpsecakmtqaazureweDocument4
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument4 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument4 = new UIHttpsecakmtqaazureweDocument4(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument4;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument5 UIHttpsecakmtqaazureweDocument5
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument5 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument5 = new UIHttpsecakmtqaazureweDocument5(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument5;
            }
        }
        
        public UIHttpsecakmtqaazureweDocument6 UIHttpsecakmtqaazureweDocument6
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument6 == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument6 = new UIHttpsecakmtqaazureweDocument6(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument6;
            }
        }
        #endregion
        
        #region Fields
        private UIAddressBarClient mUIAddressBarClient;
        
        private UIItemWindow mUIItemWindow;
        
        private UIPageControlToolBar mUIPageControlToolBar;
        
        private UISignintoAzureActiveDDocument mUISignintoAzureActiveDDocument;
        
        private UIHttpsecakmtqaazureweDocument mUIHttpsecakmtqaazureweDocument;
        
        private UIHttpsecakmtqaazureweDocument1 mUIHttpsecakmtqaazureweDocument1;
        
        private UIHttpsecakmtqaazureweDocument2 mUIHttpsecakmtqaazureweDocument2;
        
        private UIHttpsecakmtqaazureweDocument3 mUIHttpsecakmtqaazureweDocument3;
        
        private UIHttpsecakmtqaazureweDocument4 mUIHttpsecakmtqaazureweDocument4;
        
        private UIHttpsecakmtqaazureweDocument5 mUIHttpsecakmtqaazureweDocument5;
        
        private UIHttpsecakmtqaazureweDocument6 mUIHttpsecakmtqaazureweDocument6;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIAddressBarClient : WinClient
    {
        
        public UIAddressBarClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Address Bar";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIAddressandsearchusinEdit
        {
            get
            {
                if ((this.mUIAddressandsearchusinEdit == null))
                {
                    this.mUIAddressandsearchusinEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIAddressandsearchusinEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Address and search using Google";
                    this.mUIAddressandsearchusinEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIAddressandsearchusinEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIAddressandsearchusinEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Address and search using Google";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Edit";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIPageControlToolBar : WinToolBar
    {
        
        public UIPageControlToolBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinToolBar.PropertyNames.Name] = "Page Control";
            this.WindowTitles.Add("New tab");
            #endregion
        }
        
        #region Properties
        public WinButton UIGotohttpsecakmtqaazuButton
        {
            get
            {
                if ((this.mUIGotohttpsecakmtqaazuButton == null))
                {
                    this.mUIGotohttpsecakmtqaazuButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIGotohttpsecakmtqaazuButton.SearchProperties[WinButton.PropertyNames.Name] = "Go to “https://eca-kmt-qa.azurewebsites.net/” (Alt+Enter to open in a new tab)";
                    this.mUIGotohttpsecakmtqaazuButton.WindowTitles.Add("New tab");
                    #endregion
                }
                return this.mUIGotohttpsecakmtqaazuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIGotohttpsecakmtqaazuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISignintoAzureActiveDDocument : HtmlDocument
    {
        
        public UISignintoAzureActiveDDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in to Azure Active Directory";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/login.srf";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://login.microsoftonline.com/login.srf?wa=wsignin1.0&wtrealm=https%3a%2f%2flogin.windows.net&wreply=https%3a%2f%2flogin.windows.net%2fstatedept.us%2fwsfederation&wctx=3wEBD09BdXRoMkF1dGhvcml6ZQEPT0F1dGgyQXV0aG9yaXplAQxzdGF0ZWRlcHQudXMBAQEVb3BlbmlkY29ubmVjdC5pZHRva2VuAAABASRlMDM1NmU1NS1lMTI0LTQ1MmMtODM3ZC1hZWI3NTA0MTg1ZmYBJWh0dHBzOi8vZWNhLWttdC1xYS5henVyZXdlYnNpdGVzLm5ldC8AAAAAAAAAAAAAAQEaAAAAASVodHRwczovL2VjYS1rbXQtcWEuYXp1cmV3ZWJzaXRlcy5uZXQvAQkBCGFkYWxfdmVyAQUwLjAuNwEDY2lkASQwNGQyYmY0Ny0zOTJiLTQ4ZTQtOTljNy1iNjU0OTQzNTFjMTMBCWVycm9yX3VyaQElaHR0cHM6Ly9lY2Eta210LXFhLmF6dXJld2Vic2l0ZXMubmV0LwEPaW5jbHVkZV9hdF9oYXNoAQExAQtpbnRlcmFjdGl2ZQEBMQEFTm9uY2UBJDNmZjk5Y2E3LTI0NTMtNDJjMC1hNTVmLThhZmYyNmEwMmU5OQECcmMBJDc1ZjdiYzY2LTVmYWUtNGFlYS1hNTVkLTk0NTk4NGIzOGM3MgEJc2Vzc2lvbklkASQ3MGNjZjA4MS1iNmZiLTQ3MTMtODJiMy1lOTA5NGNiMjIwNjQBD2xpbWl0X3Rva2Vuc2l6ZQEBMe01&wp=MBI_FED_SSL&id=";
            this.WindowTitles.Add("Sign in to Azure Active Directory");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIUseraccountEdit
        {
            get
            {
                if ((this.mUIUseraccountEdit == null))
                {
                    this.mUIUseraccountEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_userid_inputtext";
                    this.mUIUseraccountEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "login";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "User account";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required email field normaltext";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"login\" tabindex=\"1\" class=\"login_t";
                    this.mUIUseraccountEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIUseraccountEdit.WindowTitles.Add("Sign in to Azure Active Directory");
                    #endregion
                }
                return this.mUIUseraccountEdit;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_password_inputtext";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required field normaltext";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" tabindex=\"2\" class=\"login_";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Sign in to Azure Active Directory");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlSpan UISigninPane
        {
            get
            {
                if ((this.mUISigninPane == null))
                {
                    this.mUISigninPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cred_sign_in_button";
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign in";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "button normaltext cred_sign_in_button refresh_domain_state";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"11\" class=\"button normaltext cred_sign_in_button refresh_domain_state\" " +
                        "id=\"cred_sign_in_button\" role=\"button\" style=\"opacity: 1;\" onclick=\"Post.SubmitC" +
                        "reds();return false;\"";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUISigninPane.WindowTitles.Add("Sign in to Azure Active Directory");
                    #endregion
                }
                return this.mUISigninPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIUseraccountEdit;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlSpan mUISigninPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlButton UITogglenavigationButton
        {
            get
            {
                if ((this.mUITogglenavigationButton == null))
                {
                    this.mUITogglenavigationButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Toggle navigation ";
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.Class] = "navbar-toggle collapsed";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"navbar-toggle collapsed\" type=\"bu";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUITogglenavigationButton.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUITogglenavigationButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUITogglenavigationButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument1 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlSpan UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "icon-bar";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"icon-bar\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIItemPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        
        public UICbpspmenus1Custom UICbpspmenus1Custom
        {
            get
            {
                if ((this.mUICbpspmenus1Custom == null))
                {
                    this.mUICbpspmenus1Custom = new UICbpspmenus1Custom(this);
                }
                return this.mUICbpspmenus1Custom;
            }
        }
        #endregion
        
        #region Fields
        private HtmlSpan mUIItemPane;
        
        private UICbpspmenus1Custom mUICbpspmenus1Custom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICbpspmenus1Custom : HtmlCustom
    {
        
        public UICbpspmenus1Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "NAV";
            this.SearchProperties["Id"] = "cbp-spmenu-s1";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left cbp-spmenu-open";
            this.FilterProperties["ControlDefinition"] = "class=\"cbp-spmenu cbp-spmenu-vertical cb";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIProgramsHyperlink
        {
            get
            {
                if ((this.mUIProgramsHyperlink == null))
                {
                    this.mUIProgramsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Programs";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/allprograms/";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding ng-scope";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding ng-scope\" href=\"#/allp";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIProgramsHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIProgramsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIProgramsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument2 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/allprograms/#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UICbpspmenus1Custom1 UICbpspmenus1Custom
        {
            get
            {
                if ((this.mUICbpspmenus1Custom == null))
                {
                    this.mUICbpspmenus1Custom = new UICbpspmenus1Custom1(this);
                }
                return this.mUICbpspmenus1Custom;
            }
        }
        
        public UITopPane UITopPane
        {
            get
            {
                if ((this.mUITopPane == null))
                {
                    this.mUITopPane = new UITopPane(this);
                }
                return this.mUITopPane;
            }
        }
        #endregion
        
        #region Fields
        private UICbpspmenus1Custom1 mUICbpspmenus1Custom;
        
        private UITopPane mUITopPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICbpspmenus1Custom1 : HtmlCustom
    {
        
        public UICbpspmenus1Custom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "NAV";
            this.SearchProperties["Id"] = "cbp-spmenu-s1";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left";
            this.FilterProperties["ControlDefinition"] = "class=\"cbp-spmenu cbp-spmenu-vertical cb";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIProgramsHyperlink
        {
            get
            {
                if ((this.mUIProgramsHyperlink == null))
                {
                    this.mUIProgramsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIProgramsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Programs";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/allprograms/";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding ng-scope";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding ng-scope\" href=\"#/allp";
                    this.mUIProgramsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIProgramsHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIProgramsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIProgramsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITopPane : HtmlDiv
    {
        
        public UITopPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "All Programs\r\nECA \r\n\r\n \r\n\r\nAcademic Exch";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" id=\"top\" ng-click=\"closeMenus()\" autoscroll=\"true\" ui-view=\"\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "24";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIFulbrightEnglishTeacHyperlink
        {
            get
            {
                if ((this.mUIFulbrightEnglishTeacHyperlink == null))
                {
                    this.mUIFulbrightEnglishTeacHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIFulbrightEnglishTeacHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIFulbrightEnglishTeacHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIFulbrightEnglishTeacHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIFulbrightEnglishTeacHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Fulbright English Teaching Assistant Program (ETA)";
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/offices/1/programs/133/overview";
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding";
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding\" href=\"#/offices/1/pro";
                    this.mUIFulbrightEnglishTeacHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "62";
                    this.mUIFulbrightEnglishTeacHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIFulbrightEnglishTeacHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIFulbrightEnglishTeacHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument3 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/offices/1/programs/133/overview#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UITopPane1 UITopPane
        {
            get
            {
                if ((this.mUITopPane == null))
                {
                    this.mUITopPane = new UITopPane1(this);
                }
                return this.mUITopPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopPane1 mUITopPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITopPane1 : HtmlDiv
    {
        
        public UITopPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Office of the Executive Director • Fulbr";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" id=\"top\" ng-click=\"closeMenus()\" autoscroll=\"true\" ui-view=\"\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "24";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBranchesProjectsHyperlink
        {
            get
            {
                if ((this.mUIBranchesProjectsHyperlink == null))
                {
                    this.mUIBranchesProjectsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Branches & Projects";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/offices/1/programs/133/projects";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding\" href=\"#/offices/1/pro";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIBranchesProjectsHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIBranchesProjectsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBranchesProjectsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument4 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/offices/1/programs/133/projects#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UITopPane2 UITopPane
        {
            get
            {
                if ((this.mUITopPane == null))
                {
                    this.mUITopPane = new UITopPane2(this);
                }
                return this.mUITopPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopPane2 mUITopPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITopPane2 : HtmlDiv
    {
        
        public UITopPane2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Office of the Executive Director • Fulbr";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" id=\"top\" ng-click=\"closeMenus()\" autoscroll=\"true\" ui-view=\"\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "24";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBranchesProjectsHyperlink
        {
            get
            {
                if ((this.mUIBranchesProjectsHyperlink == null))
                {
                    this.mUIBranchesProjectsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBranchesProjectsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Branches & Projects";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/offices/1/programs/133/projects";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding\" href=\"#/offices/1/pro";
                    this.mUIBranchesProjectsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIBranchesProjectsHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIBranchesProjectsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBranchesProjectsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument5 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UISortlistPane UISortlistPane
        {
            get
            {
                if ((this.mUISortlistPane == null))
                {
                    this.mUISortlistPane = new UISortlistPane(this);
                }
                return this.mUISortlistPane;
            }
        }
        #endregion
        
        #region Fields
        private UISortlistPane mUISortlistPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISortlistPane : HtmlDiv
    {
        
        public UISortlistPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "sort-list";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Title\r\n\r\nStatus\r\n\r\nYear\r\n\r\nRegion\r\n\r\n \r\n";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "id=\"sort-list\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "44";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIFulbrightETAArmenia2Hyperlink
        {
            get
            {
                if ((this.mUIFulbrightETAArmenia2Hyperlink == null))
                {
                    this.mUIFulbrightETAArmenia2Hyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIFulbrightETAArmenia2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIFulbrightETAArmenia2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIFulbrightETAArmenia2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIFulbrightETAArmenia2Hyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Fulbright ETA Armenia 2014";
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/offices/1/programs/133/project/6/overview";
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding";
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding\" href=\"#/offices/1/pro";
                    this.mUIFulbrightETAArmenia2Hyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIFulbrightETAArmenia2Hyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIFulbrightETAArmenia2Hyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIFulbrightETAArmenia2Hyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument6 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/offices/1/programs/133/project/6/overview#" +
                "top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UITopPane3 UITopPane
        {
            get
            {
                if ((this.mUITopPane == null))
                {
                    this.mUITopPane = new UITopPane3(this);
                }
                return this.mUITopPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopPane3 mUITopPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITopPane3 : HtmlDiv
    {
        
        public UITopPane3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Office of the Executive Director • Fulbr";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" id=\"top\" ng-click=\"closeMenus()\" autoscroll=\"true\" ui-view=\"\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "24";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIOverviewEnglishlanguPane
        {
            get
            {
                if ((this.mUIOverviewEnglishlanguPane == null))
                {
                    this.mUIOverviewEnglishlanguPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIOverviewEnglishlanguPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIOverviewEnglishlanguPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIOverviewEnglishlanguPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Overview\r\n\r\n\t\r\n\r\n\r\nEnglish language teac";
                    this.mUIOverviewEnglishlanguPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIOverviewEnglishlanguPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "container ng-scope";
                    this.mUIOverviewEnglishlanguPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"container ng-scope\" ui-view=\"\"";
                    this.mUIOverviewEnglishlanguPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "41";
                    this.mUIOverviewEnglishlanguPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIOverviewEnglishlanguPane;
            }
        }
        
        public HtmlButton UIDRAFTButton
        {
            get
            {
                if ((this.mUIDRAFTButton == null))
                {
                    this.mUIDRAFTButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUIDRAFTButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUIDRAFTButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUIDRAFTButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "DRAFT";
                    this.mUIDRAFTButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUIDRAFTButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUIDRAFTButton.FilterProperties[HtmlButton.PropertyNames.Class] = "btn btn-danger";
                    this.mUIDRAFTButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"btn btn-danger\" type=\"button\"";
                    this.mUIDRAFTButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUIDRAFTButton.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIDRAFTButton;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIOverviewEnglishlanguPane;
        
        private HtmlButton mUIDRAFTButton;
        #endregion
    }
}
