//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Business.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ECA.Business.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SEVISBatchCreateUpdateEV xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:noNamespaceSchemaLocation=&quot;http://www.ice.gov/xmlschema/sevisbatch/alpha/Create-UpdateExchangeVisitor.xsd&quot; xmlns:table=&quot;http://www.ice.gov/xmlschema/sevisbatch/alpha/SEVISTable.xsd&quot; xmlns:common=&quot;http://www.ice.gov/xmlschema/sevisbatch/alpha/Common.xsd&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; userID=&quot;esayya9302&quot;&gt;
        ///  &lt;BatchHeader&gt;
        ///    &lt;BatchID&gt;----kynEn47azQ&lt;/BatchID&gt;
        ///    &lt;OrgID&gt;P-1-19833&lt;/OrgID&gt;
        ///  &lt;/BatchHeader&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewParticipantWithNewDependentBatchXml {
            get {
                return ResourceManager.GetString("NewParticipantWithNewDependentBatchXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;TransactionLog xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;BatchHeader&gt;
        ///    &lt;BatchID&gt;----kynEn47azQ&lt;/BatchID&gt;
        ///    &lt;OrgID&gt;P-1-19833&lt;/OrgID&gt;
        ///  &lt;/BatchHeader&gt;
        ///  &lt;BatchDetail status=&quot;true&quot; system=&quot;PROD-ALPHA&quot;&gt;
        ///    &lt;Upload resultCode=&quot;S0000&quot; dateTimeStamp=&quot;2016-05-04T17:15:00.894+00:00&quot;&gt;
        ///      &lt;FileName&gt;batchfile3.xml&lt;/FileName&gt;
        ///    &lt;/Upload&gt;
        ///    &lt;Process resultCode=&quot;S0000&quot; dateTimeStamp=&quot;2016-05-04T17:15:06.519+00:00&quot;&gt;
        ///      &lt;RecordCount&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TransactionLogWithNewParticipantAndNewDependent {
            get {
                return ResourceManager.GetString("TransactionLogWithNewParticipantAndNewDependent", resourceCulture);
            }
        }
    }
}
