// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace ViewOrganization.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Verify the fields within the Org Profile for the Overview and the Details section.
        /// </summary>
        public void AssertIndividualOrg_OverviewDetails()
        {
            #region Variable Declarations
            HtmlDiv uIORGANIZATION911MemorPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIORGANIZATION911MemorPane;
            HtmlDiv uIDetailsWebsitehttpwwPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIDetailsWebsitehttpwwPane;
            HtmlDiv uIWebsitehttpwww911memPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIWebsitehttpwww911memPane;
            HtmlDiv uITypeOtherPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UITypeOtherPane;
            HtmlDiv uIPointsofContactPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIPointsofContactPane;
            HtmlDiv uISocialMediaPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UISocialMediaPane;
            HtmlDiv uIAddressesPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIAddressesPane;
            HtmlDiv uIItem911MemorialPane = this.UIHttpsecakmtqaazureweWindow3.UIHttpsecakmtqaazureweDocument.UITopPane.UIItem911MemorialPane;
            #endregion

            // Wait for 5 seconds for user delay between actions; Verify that the 'InnerText' property of 'ORGANIZATION 9-11 Memorial http://' pane contains 'ORGANIZATION
            //
            //9-11 Memorial
            //
            //http://www.911memorial.org/'
            Playback.Wait(5000);
            StringAssert.Contains(uIORGANIZATION911MemorPane.InnerText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIORGANIZATION911MemorPaneInnerText, "No Org banner for (9-11 Memorial) available.");

            // Verify that the 'InnerText' property of 'Details Website http://www.911' pane contains 'Details
            //
            //
            //
            //Website
            //
            //http://www.911memorial.org/ 
            //
            //
            //Type
            //
            //Other
            //
            //
            //Points of Contact
            //
            // 
            //
            //Social Media
            //
            // 
            //
            //
            //Parent Organization
            //
            //
            //
            //
            //Addresses
            //
            // '
            StringAssert.Contains(uIDetailsWebsitehttpwwPane.InnerText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIDetailsWebsitehttpwwPaneInnerText, "No Details section available for Org (9-11 Memorial)");

            // Verify that the 'DisplayText' property of 'Website http://www.911memorial.org/' pane contains 'Website
            //
            //http://www.911memorial.org/ '
            StringAssert.Contains(uIWebsitehttpwww911memPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIWebsitehttpwww911memPaneDisplayText, "Display Text for Website field does not match.");

            // Verify that the 'DisplayText' property of 'Type Other' pane contains 'Type
            //
            //Other'
            StringAssert.Contains(uITypeOtherPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UITypeOtherPaneDisplayText, "Display Text for Type field does not match.");

            // Verify that the 'DisplayText' property of 'Points of Contact' pane contains 'Points of Contact
            //
            // '
            StringAssert.Contains(uIPointsofContactPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIPointsofContactPaneDisplayText, "Display Text for Points of Contact field does not match.");

            // Verify that the 'DisplayText' property of 'Social Media' pane contains 'Social Media
            //
            // '
            StringAssert.Contains(uISocialMediaPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UISocialMediaPaneDisplayText, "Display Text for Social Media field does not match.");

            // Verify that the 'DisplayText' property of 'Addresses' pane contains 'Addresses
            //
            // '
            StringAssert.Contains(uIAddressesPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIAddressesPaneDisplayText, "Display Text for Addresses field does not match.");

            // Verify that the 'DisplayText' property of '9-11 Memorial' pane contains '9-11 Memorial'
            StringAssert.Contains(uIItem911MemorialPane.DisplayText, this.AssertIndividualOrg_OverviewDetailsExpectedValues.UIItem911MemorialPaneDisplayText, "Display Text for Overview summary field does not match.");
        }
        
        /// <summary>
        /// Verify the Organizations section exists for selection in the Content Menu.
        /// </summary>
        public void AssertOrganizations_ContentMenu()
        {
            #region Variable Declarations
            HtmlHyperlink uIOrganizationsHyperlink = this.UIHttpsecakmtqaazureweWindow.UIHttpsecakmtqaazureweDocument.UICbpspmenus1Custom.UIOrganizationsHyperlink;
            #endregion

            // Verify that the 'InnerText' property of 'Organizations' link contains 'Organizations'
            StringAssert.Contains(uIOrganizationsHyperlink.InnerText, this.AssertOrganizations_ContentMenuExpectedValues.UIOrganizationsHyperlinkInnerText, "No Organizations content menu item.");

            // Verify that the 'ControlType' property of 'Organizations' link contains 'Hyperlink'
            StringAssert.Contains(uIOrganizationsHyperlink.ControlType.ToString(), this.AssertOrganizations_ContentMenuExpectedValues.UIOrganizationsHyperlinkControlType, "Organizations is not a hyperlink in the content menu.");
        }
        
        /// <summary>
        /// Verify the sort columns (Name, Type, Status, Location); verify the Filter boxes for each column; verify the name of an org (9-11 Memorial), the type and status. (No location present.)
        /// </summary>
        public void AssertOrgList()
        {
            #region Variable Declarations
            HtmlHeaderCell uINameCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UINameCell;
            HtmlHeaderCell uITypeCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UITypeCell;
            HtmlHeaderCell uIStatusCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UIStatusCell;
            HtmlHeaderCell uILocationCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UILocationCell;
            HtmlEdit uINameFilterBox = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UINameFilterBox;
            HtmlEdit uITypeFilterBox = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UITypeFilterBox;
            HtmlEdit uIStatusFilterBox = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIStatusFilterBox;
            HtmlEdit uILocationFilterBox = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UILocationFilterBox;
            HtmlCell uIItem911MemorialCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UIItem911MemorialCell;
            HtmlCell uIOtherCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UIOtherCell;
            HtmlCell uIActiveCell = this.UIHttpsecakmtqaazureweWindow1.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItemTable.UIActiveCell;
            #endregion

            // Verify that the 'InnerText' property of 'Name' cell contains 'Name'
            StringAssert.Contains(uINameCell.InnerText, this.AssertOrgListExpectedValues.UINameCellInnerText, "No Name sort.");

            // Verify that the 'InnerText' property of 'Type' cell contains 'Type'
            StringAssert.Contains(uITypeCell.InnerText, this.AssertOrgListExpectedValues.UITypeCellInnerText, "No type sort.");

            // Verify that the 'InnerText' property of 'Status' cell contains 'Status'
            StringAssert.Contains(uIStatusCell.InnerText, this.AssertOrgListExpectedValues.UIStatusCellInnerText, "No Stauts sort.");

            // Verify that the 'InnerText' property of 'Location' cell contains 'Location'
            StringAssert.Contains(uILocationCell.InnerText, this.AssertOrgListExpectedValues.UILocationCellInnerText, "No Location sort.");

            // Verify that the 'ControlType' property of text box contains 'Edit'
            StringAssert.Contains(uINameFilterBox.ControlType.ToString(), this.AssertOrgListExpectedValues.UINameFilterBoxControlType, "No edit available for Name filter box.");

            // Verify that the 'ControlType' property of text box contains 'Edit'
            StringAssert.Contains(uITypeFilterBox.ControlType.ToString(), this.AssertOrgListExpectedValues.UITypeFilterBoxControlType, "No edit available for Type filter box.");

            // Verify that the 'ControlType' property of text box contains 'Edit'
            StringAssert.Contains(uIStatusFilterBox.ControlType.ToString(), this.AssertOrgListExpectedValues.UIStatusFilterBoxControlType, "No edit available for Status filter box.");

            // Verify that the 'ControlType' property of text box contains 'Edit'
            StringAssert.Contains(uILocationFilterBox.ControlType.ToString(), this.AssertOrgListExpectedValues.UILocationFilterBoxControlType, "No edit available for Location filter box.");

            // Verify that the 'InnerText' property of '9-11 Memorial' cell contains '9-11 Memorial'
            StringAssert.Contains(uIItem911MemorialCell.InnerText, this.AssertOrgListExpectedValues.UIItem911MemorialCellInnerText, "No (9-11 Memorial) Org available in page 1 of list. ");

            // Verify that the 'InnerText' property of 'Other' cell contains 'Other'
            StringAssert.Contains(uIOtherCell.InnerText, this.AssertOrgListExpectedValues.UIOtherCellInnerText, "No Type available for (9-11 Memorial) Org.");

            // Verify that the 'InnerText' property of 'Active' cell contains 'Active'
            StringAssert.Contains(uIActiveCell.InnerText, this.AssertOrgListExpectedValues.UIActiveCellInnerText, "No Status available for (9-11 Memorial) Org.");
        }
        
        /// <summary>
        /// Select the (9-11 Memorial) org from the list to nav to the Org Profile.
        /// </summary>
        public void SelectOrganization()
        {
            #region Variable Declarations
            HtmlHyperlink uIItem911MemorialHyperlink = this.UIHttpsecakmtqaazureweWindow2.UIHttpsecakmtqaazureweDocument.UISortlistPane.UIItem911MemorialHyperlink;
            #endregion

            // Click '9-11 Memorial' link
            Mouse.Click(uIItem911MemorialHyperlink, new Point(54, 9));
        }
        
        /// <summary>
        /// Select the Org section link from the content menu.
        /// </summary>
        public void SelectOrganizationsLink()
        {
            #region Variable Declarations
            HtmlHyperlink uIOrganizationsHyperlink = this.UIHttpsecakmtqaazureweWindow.UIHttpsecakmtqaazureweDocument.UICbpspmenus1Custom.UIOrganizationsHyperlink;
            HtmlSpan uIItemPane = this.UIHttpsecakmtqaazureweWindow.UIHttpsecakmtqaazureweDocument.UIItemPane;
            #endregion

            // Click 'Organizations' link
            Mouse.Click(uIOrganizationsHyperlink, new Point(64, 34));

            // Type '{F5}' in 'Organizations' link
            Keyboard.SendKeys(uIOrganizationsHyperlink, this.SelectOrganizationsLinkParams.UIOrganizationsHyperlinkSendKeys, ModifierKeys.None);

            // Click pane
            Mouse.Click(uIItemPane, new Point(7, 0));

            // Click 'Organizations' link
            Mouse.Click(uIOrganizationsHyperlink, new Point(65, 36));
        }
        
        /// <summary>
        /// Expand Content Menu to view Organizations section in the Content Menu.
        /// </summary>
        public void ToggleContentMenu()
        {
            #region Variable Declarations
            HtmlButton uITogglenavigationButton = this.UIHttpsecakmtqaazureweWindow.UIHttpsecakmtqaazureweDocument.UITogglenavigationButton;
            #endregion

            // Click 'Toggle navigation' button
            Mouse.Click(uITogglenavigationButton, new Point(21, 14));
        }
        
        /// <summary>
        /// Refresh/reload browser for display.
        /// </summary>
        public void RefreshBrowser()
        {
            #region Variable Declarations
            BrowserWindow uIHttpsecakmtqaazureweWindow4 = this.UIHttpsecakmtqaazureweWindow4;
            #endregion

            // Perform Refresh on Browser Window
            uIHttpsecakmtqaazureweWindow4.Refresh();
        }
        
        #region Properties
        public virtual AssertIndividualOrg_OverviewDetailsExpectedValues AssertIndividualOrg_OverviewDetailsExpectedValues
        {
            get
            {
                if ((this.mAssertIndividualOrg_OverviewDetailsExpectedValues == null))
                {
                    this.mAssertIndividualOrg_OverviewDetailsExpectedValues = new AssertIndividualOrg_OverviewDetailsExpectedValues();
                }
                return this.mAssertIndividualOrg_OverviewDetailsExpectedValues;
            }
        }
        
        public virtual AssertOrganizations_ContentMenuExpectedValues AssertOrganizations_ContentMenuExpectedValues
        {
            get
            {
                if ((this.mAssertOrganizations_ContentMenuExpectedValues == null))
                {
                    this.mAssertOrganizations_ContentMenuExpectedValues = new AssertOrganizations_ContentMenuExpectedValues();
                }
                return this.mAssertOrganizations_ContentMenuExpectedValues;
            }
        }
        
        public virtual AssertOrgListExpectedValues AssertOrgListExpectedValues
        {
            get
            {
                if ((this.mAssertOrgListExpectedValues == null))
                {
                    this.mAssertOrgListExpectedValues = new AssertOrgListExpectedValues();
                }
                return this.mAssertOrgListExpectedValues;
            }
        }
        
        public virtual SelectOrganizationsLinkParams SelectOrganizationsLinkParams
        {
            get
            {
                if ((this.mSelectOrganizationsLinkParams == null))
                {
                    this.mSelectOrganizationsLinkParams = new SelectOrganizationsLinkParams();
                }
                return this.mSelectOrganizationsLinkParams;
            }
        }
        
        public UINewtabInternetExplorWindow UINewtabInternetExplorWindow
        {
            get
            {
                if ((this.mUINewtabInternetExplorWindow == null))
                {
                    this.mUINewtabInternetExplorWindow = new UINewtabInternetExplorWindow();
                }
                return this.mUINewtabInternetExplorWindow;
            }
        }
        
        public UIHttpsecakmtqaazureweWindow UIHttpsecakmtqaazureweWindow
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweWindow == null))
                {
                    this.mUIHttpsecakmtqaazureweWindow = new UIHttpsecakmtqaazureweWindow();
                }
                return this.mUIHttpsecakmtqaazureweWindow;
            }
        }
        
        public UIHttpsecakmtqaazureweWindow1 UIHttpsecakmtqaazureweWindow1
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweWindow1 == null))
                {
                    this.mUIHttpsecakmtqaazureweWindow1 = new UIHttpsecakmtqaazureweWindow1();
                }
                return this.mUIHttpsecakmtqaazureweWindow1;
            }
        }
        
        public UIHttpsecakmtqaazureweWindow2 UIHttpsecakmtqaazureweWindow2
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweWindow2 == null))
                {
                    this.mUIHttpsecakmtqaazureweWindow2 = new UIHttpsecakmtqaazureweWindow2();
                }
                return this.mUIHttpsecakmtqaazureweWindow2;
            }
        }
        
        public UIHttpsecakmtqaazureweWindow3 UIHttpsecakmtqaazureweWindow3
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweWindow3 == null))
                {
                    this.mUIHttpsecakmtqaazureweWindow3 = new UIHttpsecakmtqaazureweWindow3();
                }
                return this.mUIHttpsecakmtqaazureweWindow3;
            }
        }
        
        public UIHttpsecakmtqaazureweWindow4 UIHttpsecakmtqaazureweWindow4
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweWindow4 == null))
                {
                    this.mUIHttpsecakmtqaazureweWindow4 = new UIHttpsecakmtqaazureweWindow4();
                }
                return this.mUIHttpsecakmtqaazureweWindow4;
            }
        }
        #endregion
        
        #region Fields
        private AssertIndividualOrg_OverviewDetailsExpectedValues mAssertIndividualOrg_OverviewDetailsExpectedValues;
        
        private AssertOrganizations_ContentMenuExpectedValues mAssertOrganizations_ContentMenuExpectedValues;
        
        private AssertOrgListExpectedValues mAssertOrgListExpectedValues;
        
        private SelectOrganizationsLinkParams mSelectOrganizationsLinkParams;
        
        private UINewtabInternetExplorWindow mUINewtabInternetExplorWindow;
        
        private UIHttpsecakmtqaazureweWindow mUIHttpsecakmtqaazureweWindow;
        
        private UIHttpsecakmtqaazureweWindow1 mUIHttpsecakmtqaazureweWindow1;
        
        private UIHttpsecakmtqaazureweWindow2 mUIHttpsecakmtqaazureweWindow2;
        
        private UIHttpsecakmtqaazureweWindow3 mUIHttpsecakmtqaazureweWindow3;
        
        private UIHttpsecakmtqaazureweWindow4 mUIHttpsecakmtqaazureweWindow4;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertIndividualOrg_OverviewDetails'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertIndividualOrg_OverviewDetailsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Wait for 5 seconds for user delay between actions; Verify that the 'InnerText' property of 'ORGANIZATION 9-11 Memorial http://' pane contains 'ORGANIZATION
        ///
        ///9-11 Memorial
        ///
        ///http://www.911memorial.org/'
        /// </summary>
        public string UIORGANIZATION911MemorPaneInnerText = "ORGANIZATION\r\n\r\n9-11 Memorial\r\n\r\nhttp://www.911memorial.org/";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Details Website http://www.911' pane contains 'Details
        ///
        ///
        ///
        ///Website
        ///
        ///http://www.911memorial.org/ 
        ///
        ///
        ///Type
        ///
        ///Other
        ///
        ///
        ///Points of Contact
        ///
        /// 
        ///
        ///Social Media
        ///
        /// 
        ///
        ///
        ///Parent Organization
        ///
        ///
        ///
        ///
        ///Addresses
        ///
        /// '
        /// </summary>
        public string UIDetailsWebsitehttpwwPaneInnerText = "Details\r\n\r\n\r\n\r\nWebsite\r\n\r\nhttp://www.911memorial.org/ \r\n\r\n\r\nType\r\n\r\nOther\r\n\r\n\r\nPo" +
            "ints of Contact\r\n\r\n \r\n\r\nSocial Media\r\n\r\n \r\n\r\n\r\nParent Organization\r\n\r\n\r\n\r\n\r\nAddr" +
            "esses\r\n\r\n ";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Website http://www.911memorial.org/' pane contains 'Website
        ///
        ///http://www.911memorial.org/ '
        /// </summary>
        public string UIWebsitehttpwww911memPaneDisplayText = "Website\r\n\r\nhttp://www.911memorial.org/ ";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Type Other' pane contains 'Type
        ///
        ///Other'
        /// </summary>
        public string UITypeOtherPaneDisplayText = "Type\r\n\r\nOther";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Points of Contact' pane contains 'Points of Contact
        ///
        /// '
        /// </summary>
        public string UIPointsofContactPaneDisplayText = "Points of Contact\r\n\r\n ";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Social Media' pane contains 'Social Media
        ///
        /// '
        /// </summary>
        public string UISocialMediaPaneDisplayText = "Social Media\r\n\r\n ";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of 'Addresses' pane contains 'Addresses
        ///
        /// '
        /// </summary>
        public string UIAddressesPaneDisplayText = "Addresses\r\n\r\n ";
        
        /// <summary>
        /// Verify that the 'DisplayText' property of '9-11 Memorial' pane contains '9-11 Memorial'
        /// </summary>
        public string UIItem911MemorialPaneDisplayText = "9-11 Memorial";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertOrganizations_ContentMenu'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertOrganizations_ContentMenuExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Organizations' link contains 'Organizations'
        /// </summary>
        public string UIOrganizationsHyperlinkInnerText = "Organizations";
        
        /// <summary>
        /// Verify that the 'ControlType' property of 'Organizations' link contains 'Hyperlink'
        /// </summary>
        public string UIOrganizationsHyperlinkControlType = "Hyperlink";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertOrgList'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class AssertOrgListExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of 'Name' cell contains 'Name'
        /// </summary>
        public string UINameCellInnerText = "Name";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Type' cell contains 'Type'
        /// </summary>
        public string UITypeCellInnerText = "Type";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Status' cell contains 'Status'
        /// </summary>
        public string UIStatusCellInnerText = "Status";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Location' cell contains 'Location'
        /// </summary>
        public string UILocationCellInnerText = "Location";
        
        /// <summary>
        /// Verify that the 'ControlType' property of text box contains 'Edit'
        /// </summary>
        public string UINameFilterBoxControlType = "Edit";
        
        /// <summary>
        /// Verify that the 'ControlType' property of text box contains 'Edit'
        /// </summary>
        public string UITypeFilterBoxControlType = "Edit";
        
        /// <summary>
        /// Verify that the 'ControlType' property of text box contains 'Edit'
        /// </summary>
        public string UIStatusFilterBoxControlType = "Edit";
        
        /// <summary>
        /// Verify that the 'ControlType' property of text box contains 'Edit'
        /// </summary>
        public string UILocationFilterBoxControlType = "Edit";
        
        /// <summary>
        /// Verify that the 'InnerText' property of '9-11 Memorial' cell contains '9-11 Memorial'
        /// </summary>
        public string UIItem911MemorialCellInnerText = "9-11 Memorial";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Other' cell contains 'Other'
        /// </summary>
        public string UIOtherCellInnerText = "Other";
        
        /// <summary>
        /// Verify that the 'InnerText' property of 'Active' cell contains 'Active'
        /// </summary>
        public string UIActiveCellInnerText = "Active";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'SelectOrganizationsLink'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class SelectOrganizationsLinkParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{F5}' in 'Organizations' link
        /// </summary>
        public string UIOrganizationsHyperlinkSendKeys = "{F5}";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UINewtabInternetExplorWindow : BrowserWindow
    {
        
        public UINewtabInternetExplorWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "New tab";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("New tab");
            this.WindowTitles.Add("Sign in to ECA Client");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UISignintoECAClientDocument UISignintoECAClientDocument
        {
            get
            {
                if ((this.mUISignintoECAClientDocument == null))
                {
                    this.mUISignintoECAClientDocument = new UISignintoECAClientDocument(this);
                }
                return this.mUISignintoECAClientDocument;
            }
        }
        #endregion
        
        #region Fields
        private UISignintoECAClientDocument mUISignintoECAClientDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISignintoECAClientDocument : HtmlDocument
    {
        
        public UISignintoECAClientDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Sign in to ECA Client";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/statedept.us/oauth2/authorize";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = @"https://login.microsoftonline.com/statedept.us/oauth2/authorize?response_type=id_token&client_id=e0356e55-e124-452c-837d-aeb7504185ff&redirect_uri=https%3A%2F%2Feca-kmt-qa.azurewebsites.net%2F&state=4f728204-270f-415c-af84-3a3628002155&x-client-SKU=Js&x-client-Ver=1.0.0&nonce=82893122-d9a5-4f3f-bd3e-a30fa445ea6f";
            this.WindowTitles.Add("Sign in to ECA Client");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIECATest1statedeptusHyperlink
        {
            get
            {
                if ((this.mUIECATest1statedeptusHyperlink == null))
                {
                    this.mUIECATest1statedeptusHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIECATest1statedeptusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = "ecatest1_statedept_us_link";
                    this.mUIECATest1statedeptusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIECATest1statedeptusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIECATest1statedeptusHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "\r\nECATest1@statedept.us\r\n\r\n\r\n\r\n•••";
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#";
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "tile_link tooltip";
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "tabindex=\"1\" class=\"tile_link tooltip\" i";
                    this.mUIECATest1statedeptusHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIECATest1statedeptusHyperlink.WindowTitles.Add("Sign in to ECA Client");
                    #endregion
                }
                return this.mUIECATest1statedeptusHyperlink;
            }
        }
        
        public HtmlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "cred_password_inputtext";
                    this.mUIPasswordEdit.SearchProperties[HtmlEdit.PropertyNames.Name] = "passwd";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.LabeledBy] = "Password";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Type] = "PASSWORD";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "login_textfield textfield required field normaltext";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "name=\"passwd\" tabindex=\"2\" class=\"login_";
                    this.mUIPasswordEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUIPasswordEdit.WindowTitles.Add("Sign in to ECA Client");
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public HtmlSpan UISigninPane
        {
            get
            {
                if ((this.mUISigninPane == null))
                {
                    this.mUISigninPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Id] = "cred_sign_in_button";
                    this.mUISigninPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Sign in";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "button normaltext cred_sign_in_button refresh_domain_state control-button button-" +
                        "two button_primary";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "tabindex=\"11\" class=\"button normaltext cred_sign_in_button refresh_domain_state c" +
                        "ontrol-button button-two button_primary\" id=\"cred_sign_in_button\" role=\"button\" " +
                        "style=\"opacity: 1;\"";
                    this.mUISigninPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "11";
                    this.mUISigninPane.WindowTitles.Add("Sign in to ECA Client");
                    #endregion
                }
                return this.mUISigninPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIECATest1statedeptusHyperlink;
        
        private HtmlEdit mUIPasswordEdit;
        
        private HtmlSpan mUISigninPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweWindow : BrowserWindow
    {
        
        public UIHttpsecakmtqaazureweWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://eca-kmt-qa.azurewebsites.net/";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsecakmtqaazureweDocument UIHttpsecakmtqaazureweDocument
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument = new UIHttpsecakmtqaazureweDocument(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsecakmtqaazureweDocument mUIHttpsecakmtqaazureweDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlButton UITogglenavigationButton
        {
            get
            {
                if ((this.mUITogglenavigationButton == null))
                {
                    this.mUITogglenavigationButton = new HtmlButton(this);
                    #region Search Criteria
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Id] = null;
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Name] = null;
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.DisplayText] = "Toggle navigation ";
                    this.mUITogglenavigationButton.SearchProperties[HtmlButton.PropertyNames.Type] = "button";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.Title] = null;
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.Class] = "navbar-toggle collapsed";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.ControlDefinition] = "class=\"navbar-toggle collapsed\" type=\"bu";
                    this.mUITogglenavigationButton.FilterProperties[HtmlButton.PropertyNames.TagInstance] = "1";
                    this.mUITogglenavigationButton.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUITogglenavigationButton;
            }
        }
        
        public UICbpspmenus1Custom UICbpspmenus1Custom
        {
            get
            {
                if ((this.mUICbpspmenus1Custom == null))
                {
                    this.mUICbpspmenus1Custom = new UICbpspmenus1Custom(this);
                }
                return this.mUICbpspmenus1Custom;
            }
        }
        
        public HtmlSpan UIItemPane
        {
            get
            {
                if ((this.mUIItemPane == null))
                {
                    this.mUIItemPane = new HtmlSpan(this);
                    #region Search Criteria
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItemPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "icon-bar";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"icon-bar\"";
                    this.mUIItemPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "4";
                    this.mUIItemPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItemPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlButton mUITogglenavigationButton;
        
        private UICbpspmenus1Custom mUICbpspmenus1Custom;
        
        private HtmlSpan mUIItemPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UICbpspmenus1Custom : HtmlCustom
    {
        
        public UICbpspmenus1Custom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["TagName"] = "NAV";
            this.SearchProperties["Id"] = "cbp-spmenu-s1";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.FilterProperties["Class"] = "cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left cbp-spmenu-open";
            this.FilterProperties["ControlDefinition"] = "class=\"cbp-spmenu cbp-spmenu-vertical cb";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIOrganizationsHyperlink
        {
            get
            {
                if ((this.mUIOrganizationsHyperlink == null))
                {
                    this.mUIOrganizationsHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIOrganizationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIOrganizationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIOrganizationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIOrganizationsHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Organizations";
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/allorganizations";
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding ng-scope";
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding ng-scope\" href=\"#/allo";
                    this.mUIOrganizationsHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "5";
                    this.mUIOrganizationsHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIOrganizationsHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIOrganizationsHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweWindow1 : BrowserWindow
    {
        
        public UIHttpsecakmtqaazureweWindow1()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://eca-kmt-qa.azurewebsites.net/";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsecakmtqaazureweDocument1 UIHttpsecakmtqaazureweDocument
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument = new UIHttpsecakmtqaazureweDocument1(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsecakmtqaazureweDocument1 mUIHttpsecakmtqaazureweDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument1 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/allorganizations#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UISortlistPane UISortlistPane
        {
            get
            {
                if ((this.mUISortlistPane == null))
                {
                    this.mUISortlistPane = new UISortlistPane(this);
                }
                return this.mUISortlistPane;
            }
        }
        #endregion
        
        #region Fields
        private UISortlistPane mUISortlistPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISortlistPane : HtmlDiv
    {
        
        public UISortlistPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "sort-list";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Name\r\n\r\nType\r\n\r\nStatus\r\n\r\nLocation\r\n\r\n \r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-isolate-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-isolate-scope\" id=\"sort-list\" st-table=\"organizations\" st-pipe=\"getOrga" +
                "nizations\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "31";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UIItemTable UIItemTable
        {
            get
            {
                if ((this.mUIItemTable == null))
                {
                    this.mUIItemTable = new UIItemTable(this);
                }
                return this.mUIItemTable;
            }
        }
        
        public HtmlEdit UINameFilterBox
        {
            get
            {
                if ((this.mUINameFilterBox == null))
                {
                    this.mUINameFilterBox = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUINameFilterBox.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUINameFilterBox.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUINameFilterBox.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUINameFilterBox.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUINameFilterBox.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUINameFilterBox.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-lg form-control";
                    this.mUINameFilterBox.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"input-lg form-control\" type=\"sear";
                    this.mUINameFilterBox.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUINameFilterBox.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUINameFilterBox;
            }
        }
        
        public HtmlEdit UITypeFilterBox
        {
            get
            {
                if ((this.mUITypeFilterBox == null))
                {
                    this.mUITypeFilterBox = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUITypeFilterBox.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUITypeFilterBox.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUITypeFilterBox.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUITypeFilterBox.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUITypeFilterBox.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUITypeFilterBox.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-lg form-control";
                    this.mUITypeFilterBox.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"input-lg form-control\" type=\"sear";
                    this.mUITypeFilterBox.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "2";
                    this.mUITypeFilterBox.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUITypeFilterBox;
            }
        }
        
        public HtmlEdit UIStatusFilterBox
        {
            get
            {
                if ((this.mUIStatusFilterBox == null))
                {
                    this.mUIStatusFilterBox = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIStatusFilterBox.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUIStatusFilterBox.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUIStatusFilterBox.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUIStatusFilterBox.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUIStatusFilterBox.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIStatusFilterBox.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-lg form-control";
                    this.mUIStatusFilterBox.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"input-lg form-control\" type=\"sear";
                    this.mUIStatusFilterBox.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "3";
                    this.mUIStatusFilterBox.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIStatusFilterBox;
            }
        }
        
        public HtmlEdit UILocationFilterBox
        {
            get
            {
                if ((this.mUILocationFilterBox == null))
                {
                    this.mUILocationFilterBox = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUILocationFilterBox.SearchProperties[HtmlEdit.PropertyNames.Id] = null;
                    this.mUILocationFilterBox.SearchProperties[HtmlEdit.PropertyNames.Name] = null;
                    this.mUILocationFilterBox.SearchProperties[HtmlEdit.PropertyNames.LabeledBy] = null;
                    this.mUILocationFilterBox.SearchProperties[HtmlEdit.PropertyNames.Type] = "SINGLELINE";
                    this.mUILocationFilterBox.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUILocationFilterBox.FilterProperties[HtmlEdit.PropertyNames.Class] = "input-lg form-control";
                    this.mUILocationFilterBox.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "class=\"input-lg form-control\" type=\"sear";
                    this.mUILocationFilterBox.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "4";
                    this.mUILocationFilterBox.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUILocationFilterBox;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTable mUIItemTable;
        
        private HtmlEdit mUINameFilterBox;
        
        private HtmlEdit mUITypeFilterBox;
        
        private HtmlEdit mUIStatusFilterBox;
        
        private HtmlEdit mUILocationFilterBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIItemTable : HtmlTable
    {
        
        public UIItemTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlTable.PropertyNames.Id] = null;
            this.SearchProperties[HtmlTable.PropertyNames.Name] = null;
            this.FilterProperties[HtmlTable.PropertyNames.InnerText] = "Name\r\n\r\nType\r\n\r\nStatus\r\n\r\nLocation\r\n\r\n \r";
            this.FilterProperties[HtmlTable.PropertyNames.ControlDefinition] = "class=\"col-md-12 alt\"";
            this.FilterProperties[HtmlTable.PropertyNames.RowCount] = "28";
            this.FilterProperties[HtmlTable.PropertyNames.ColumnCount] = "5";
            this.FilterProperties[HtmlTable.PropertyNames.Class] = "col-md-12 alt";
            this.FilterProperties[HtmlTable.PropertyNames.TagInstance] = "1";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHeaderCell UINameCell
        {
            get
            {
                if ((this.mUINameCell == null))
                {
                    this.mUINameCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUINameCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUINameCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUINameCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUINameCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Name";
                    this.mUINameCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"col-md-4 sort-label medium st-sort-ascent\" st-sort-default=\"true\" st-sort=" +
                        "\"\'name\'\"";
                    this.mUINameCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUINameCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUINameCell.FilterProperties[HtmlCell.PropertyNames.Class] = "col-md-4 sort-label medium st-sort-ascent";
                    this.mUINameCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUINameCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUINameCell;
            }
        }
        
        public HtmlHeaderCell UITypeCell
        {
            get
            {
                if ((this.mUITypeCell == null))
                {
                    this.mUITypeCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUITypeCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUITypeCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUITypeCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUITypeCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Type";
                    this.mUITypeCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"col-md-3 sort-label medium\" st-sort=\"\'organizationType\'\"";
                    this.mUITypeCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUITypeCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUITypeCell.FilterProperties[HtmlCell.PropertyNames.Class] = "col-md-3 sort-label medium";
                    this.mUITypeCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUITypeCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUITypeCell;
            }
        }
        
        public HtmlHeaderCell UIStatusCell
        {
            get
            {
                if ((this.mUIStatusCell == null))
                {
                    this.mUIStatusCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUIStatusCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIStatusCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIStatusCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIStatusCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Status";
                    this.mUIStatusCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"col-md-1 sort-label medium\" st-sort=\"\'status\'\"";
                    this.mUIStatusCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUIStatusCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIStatusCell.FilterProperties[HtmlCell.PropertyNames.Class] = "col-md-1 sort-label medium";
                    this.mUIStatusCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "3";
                    this.mUIStatusCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIStatusCell;
            }
        }
        
        public HtmlHeaderCell UILocationCell
        {
            get
            {
                if ((this.mUILocationCell == null))
                {
                    this.mUILocationCell = new HtmlHeaderCell(this);
                    #region Search Criteria
                    this.mUILocationCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUILocationCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUILocationCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUILocationCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Location";
                    this.mUILocationCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"col-md-2 sort-label medium\" st-sort=\"\'location\'\"";
                    this.mUILocationCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "0";
                    this.mUILocationCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "3";
                    this.mUILocationCell.FilterProperties[HtmlCell.PropertyNames.Class] = "col-md-2 sort-label medium";
                    this.mUILocationCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "4";
                    this.mUILocationCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUILocationCell;
            }
        }
        
        public HtmlCell UIItem911MemorialCell
        {
            get
            {
                if ((this.mUIItem911MemorialCell == null))
                {
                    this.mUIItem911MemorialCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItem911MemorialCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItem911MemorialCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItem911MemorialCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItem911MemorialCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "9-11 Memorial";
                    this.mUIItem911MemorialCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = null;
                    this.mUIItem911MemorialCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIItem911MemorialCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "0";
                    this.mUIItem911MemorialCell.FilterProperties[HtmlCell.PropertyNames.Class] = null;
                    this.mUIItem911MemorialCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "1";
                    this.mUIItem911MemorialCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItem911MemorialCell;
            }
        }
        
        public HtmlCell UIOtherCell
        {
            get
            {
                if ((this.mUIOtherCell == null))
                {
                    this.mUIOtherCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIOtherCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIOtherCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIOtherCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIOtherCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Other";
                    this.mUIOtherCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"ng-binding\"";
                    this.mUIOtherCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIOtherCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "1";
                    this.mUIOtherCell.FilterProperties[HtmlCell.PropertyNames.Class] = "ng-binding";
                    this.mUIOtherCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "2";
                    this.mUIOtherCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIOtherCell;
            }
        }
        
        public HtmlCell UIActiveCell
        {
            get
            {
                if ((this.mUIActiveCell == null))
                {
                    this.mUIActiveCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIActiveCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIActiveCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIActiveCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIActiveCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = "Active";
                    this.mUIActiveCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"ng-binding\"";
                    this.mUIActiveCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIActiveCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "2";
                    this.mUIActiveCell.FilterProperties[HtmlCell.PropertyNames.Class] = "ng-binding";
                    this.mUIActiveCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "3";
                    this.mUIActiveCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIActiveCell;
            }
        }
        
        public HtmlCell UIItemCell
        {
            get
            {
                if ((this.mUIItemCell == null))
                {
                    this.mUIItemCell = new HtmlCell(this);
                    #region Search Criteria
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Id] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.Name] = null;
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.MaxDepth] = "3";
                    this.mUIItemCell.SearchProperties[HtmlCell.PropertyNames.InnerText] = null;
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ControlDefinition] = "class=\"ng-binding\"";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.RowIndex] = "2";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.ColumnIndex] = "3";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.Class] = "ng-binding";
                    this.mUIItemCell.FilterProperties[HtmlCell.PropertyNames.TagInstance] = "4";
                    this.mUIItemCell.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItemCell;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHeaderCell mUINameCell;
        
        private HtmlHeaderCell mUITypeCell;
        
        private HtmlHeaderCell mUIStatusCell;
        
        private HtmlHeaderCell mUILocationCell;
        
        private HtmlCell mUIItem911MemorialCell;
        
        private HtmlCell mUIOtherCell;
        
        private HtmlCell mUIActiveCell;
        
        private HtmlCell mUIItemCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweWindow2 : BrowserWindow
    {
        
        public UIHttpsecakmtqaazureweWindow2()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://eca-kmt-qa.azurewebsites.net/";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsecakmtqaazureweDocument2 UIHttpsecakmtqaazureweDocument
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument = new UIHttpsecakmtqaazureweDocument2(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsecakmtqaazureweDocument2 mUIHttpsecakmtqaazureweDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument2 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UISortlistPane1 UISortlistPane
        {
            get
            {
                if ((this.mUISortlistPane == null))
                {
                    this.mUISortlistPane = new UISortlistPane1(this);
                }
                return this.mUISortlistPane;
            }
        }
        #endregion
        
        #region Fields
        private UISortlistPane1 mUISortlistPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UISortlistPane1 : HtmlDiv
    {
        
        public UISortlistPane1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "sort-list";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Name\r\n\r\nType\r\n\r\nStatus\r\n\r\nLocation\r\n\r\n \r";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-isolate-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-isolate-scope\" id=\"sort-list\" st-table=\"organizations\" st-pipe=\"getOrga" +
                "nizations\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "31";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIItem911MemorialHyperlink
        {
            get
            {
                if ((this.mUIItem911MemorialHyperlink == null))
                {
                    this.mUIItem911MemorialHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIItem911MemorialHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIItem911MemorialHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIItem911MemorialHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIItem911MemorialHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "9-11 Memorial";
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = null;
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "#/organizations/2127/overview";
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = "ng-binding";
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "class=\"ng-binding\" href=\"#/organizations";
                    this.mUIItem911MemorialHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "1";
                    this.mUIItem911MemorialHyperlink.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItem911MemorialHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIItem911MemorialHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweWindow3 : BrowserWindow
    {
        
        public UIHttpsecakmtqaazureweWindow3()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://eca-kmt-qa.azurewebsites.net/";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHttpsecakmtqaazureweDocument3 UIHttpsecakmtqaazureweDocument
        {
            get
            {
                if ((this.mUIHttpsecakmtqaazureweDocument == null))
                {
                    this.mUIHttpsecakmtqaazureweDocument = new UIHttpsecakmtqaazureweDocument3(this);
                }
                return this.mUIHttpsecakmtqaazureweDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHttpsecakmtqaazureweDocument3 mUIHttpsecakmtqaazureweDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweDocument3 : HtmlDocument
    {
        
        public UIHttpsecakmtqaazureweDocument3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "https://eca-kmt-qa.azurewebsites.net/#/organizations/2127/overview#top";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public UITopPane UITopPane
        {
            get
            {
                if ((this.mUITopPane == null))
                {
                    this.mUITopPane = new UITopPane(this);
                }
                return this.mUITopPane;
            }
        }
        #endregion
        
        #region Fields
        private UITopPane mUITopPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UITopPane : HtmlDiv
    {
        
        public UITopPane(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDiv.PropertyNames.Id] = "top";
            this.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "9-11 Memorial \r\n \r\n\r\n\r\nLast Updated Mar ";
            this.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
            this.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" id=\"top\" autoscroll=\"true\" ui-view=\"\"";
            this.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "27";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        #region Properties
        public HtmlDiv UIORGANIZATION911MemorPane
        {
            get
            {
                if ((this.mUIORGANIZATION911MemorPane == null))
                {
                    this.mUIORGANIZATION911MemorPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIORGANIZATION911MemorPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIORGANIZATION911MemorPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIORGANIZATION911MemorPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "ORGANIZATION\r\n\r\n9-11 Memorial\r\n\r\nhttp://";
                    this.mUIORGANIZATION911MemorPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIORGANIZATION911MemorPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "heading";
                    this.mUIORGANIZATION911MemorPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"heading\"";
                    this.mUIORGANIZATION911MemorPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "33";
                    this.mUIORGANIZATION911MemorPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIORGANIZATION911MemorPane;
            }
        }
        
        public HtmlDiv UIOverview911MemorialDPane
        {
            get
            {
                if ((this.mUIOverview911MemorialDPane == null))
                {
                    this.mUIOverview911MemorialDPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIOverview911MemorialDPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIOverview911MemorialDPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIOverview911MemorialDPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Overview\r\n\r\n\r\n9-11 Memorial\r\n\r\n \r\n\r\n\r\nDe";
                    this.mUIOverview911MemorialDPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIOverview911MemorialDPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "ng-scope";
                    this.mUIOverview911MemorialDPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"ng-scope\" ng-show=\"!view.isOrganizationLoading\"";
                    this.mUIOverview911MemorialDPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "47";
                    this.mUIOverview911MemorialDPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIOverview911MemorialDPane;
            }
        }
        
        public HtmlDiv UIDetailsWebsitehttpwwPane
        {
            get
            {
                if ((this.mUIDetailsWebsitehttpwwPane == null))
                {
                    this.mUIDetailsWebsitehttpwwPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIDetailsWebsitehttpwwPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIDetailsWebsitehttpwwPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIDetailsWebsitehttpwwPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Details\r\n\r\n\r\n\r\nWebsite\r\n\r\nhttp://www.911";
                    this.mUIDetailsWebsitehttpwwPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIDetailsWebsitehttpwwPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row table";
                    this.mUIDetailsWebsitehttpwwPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row table\"";
                    this.mUIDetailsWebsitehttpwwPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "50";
                    this.mUIDetailsWebsitehttpwwPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIDetailsWebsitehttpwwPane;
            }
        }
        
        public HtmlDiv UIWebsitePane
        {
            get
            {
                if ((this.mUIWebsitePane == null))
                {
                    this.mUIWebsitePane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWebsitePane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWebsitePane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWebsitePane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Website";
                    this.mUIWebsitePane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWebsitePane.FilterProperties[HtmlDiv.PropertyNames.Class] = "col-md-6 title-label";
                    this.mUIWebsitePane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"col-md-6 title-label\"";
                    this.mUIWebsitePane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "53";
                    this.mUIWebsitePane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIWebsitePane;
            }
        }
        
        public HtmlDiv UIWebsitehttpwww911memPane
        {
            get
            {
                if ((this.mUIWebsitehttpwww911memPane == null))
                {
                    this.mUIWebsitehttpwww911memPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIWebsitehttpwww911memPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIWebsitehttpwww911memPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIWebsitehttpwww911memPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Website\r\n\r\nhttp://www.911memorial.org/ ";
                    this.mUIWebsitehttpwww911memPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIWebsitehttpwww911memPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIWebsitehttpwww911memPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\" ng-show=\"organization.website\"";
                    this.mUIWebsitehttpwww911memPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "52";
                    this.mUIWebsitehttpwww911memPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIWebsitehttpwww911memPane;
            }
        }
        
        public HtmlDiv UITypeOtherPane
        {
            get
            {
                if ((this.mUITypeOtherPane == null))
                {
                    this.mUITypeOtherPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUITypeOtherPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUITypeOtherPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUITypeOtherPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Type\r\n\r\nOther";
                    this.mUITypeOtherPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUITypeOtherPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUITypeOtherPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\"";
                    this.mUITypeOtherPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "55";
                    this.mUITypeOtherPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUITypeOtherPane;
            }
        }
        
        public HtmlDiv UIPointsofContactPane
        {
            get
            {
                if ((this.mUIPointsofContactPane == null))
                {
                    this.mUIPointsofContactPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIPointsofContactPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIPointsofContactPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIPointsofContactPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Points of Contact\r\n\r\n ";
                    this.mUIPointsofContactPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIPointsofContactPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIPointsofContactPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\" ng-show=\"organization.contacts\"";
                    this.mUIPointsofContactPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "58";
                    this.mUIPointsofContactPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIPointsofContactPane;
            }
        }
        
        public HtmlDiv UISocialMediaPane
        {
            get
            {
                if ((this.mUISocialMediaPane == null))
                {
                    this.mUISocialMediaPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUISocialMediaPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUISocialMediaPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUISocialMediaPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Social Media\r\n\r\n ";
                    this.mUISocialMediaPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUISocialMediaPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUISocialMediaPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\" ng-show=\"organization.socialMedias\"";
                    this.mUISocialMediaPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "61";
                    this.mUISocialMediaPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUISocialMediaPane;
            }
        }
        
        public HtmlDiv UIAddressesPane
        {
            get
            {
                if ((this.mUIAddressesPane == null))
                {
                    this.mUIAddressesPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIAddressesPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIAddressesPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIAddressesPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "Addresses\r\n\r\n ";
                    this.mUIAddressesPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIAddressesPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIAddressesPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\"";
                    this.mUIAddressesPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "68";
                    this.mUIAddressesPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIAddressesPane;
            }
        }
        
        public HtmlDiv UIItem911MemorialPane
        {
            get
            {
                if ((this.mUIItem911MemorialPane == null))
                {
                    this.mUIItem911MemorialPane = new HtmlDiv(this);
                    #region Search Criteria
                    this.mUIItem911MemorialPane.SearchProperties[HtmlDiv.PropertyNames.Id] = null;
                    this.mUIItem911MemorialPane.SearchProperties[HtmlDiv.PropertyNames.Name] = null;
                    this.mUIItem911MemorialPane.FilterProperties[HtmlDiv.PropertyNames.InnerText] = "9-11 Memorial";
                    this.mUIItem911MemorialPane.FilterProperties[HtmlDiv.PropertyNames.Title] = null;
                    this.mUIItem911MemorialPane.FilterProperties[HtmlDiv.PropertyNames.Class] = "row";
                    this.mUIItem911MemorialPane.FilterProperties[HtmlDiv.PropertyNames.ControlDefinition] = "class=\"row\"";
                    this.mUIItem911MemorialPane.FilterProperties[HtmlDiv.PropertyNames.TagInstance] = "48";
                    this.mUIItem911MemorialPane.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
                    #endregion
                }
                return this.mUIItem911MemorialPane;
            }
        }
        #endregion
        
        #region Fields
        private HtmlDiv mUIORGANIZATION911MemorPane;
        
        private HtmlDiv mUIOverview911MemorialDPane;
        
        private HtmlDiv mUIDetailsWebsitehttpwwPane;
        
        private HtmlDiv mUIWebsitePane;
        
        private HtmlDiv mUIWebsitehttpwww911memPane;
        
        private HtmlDiv mUITypeOtherPane;
        
        private HtmlDiv mUIPointsofContactPane;
        
        private HtmlDiv mUISocialMediaPane;
        
        private HtmlDiv mUIAddressesPane;
        
        private HtmlDiv mUIItem911MemorialPane;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class UIHttpsecakmtqaazureweWindow4 : BrowserWindow
    {
        
        public UIHttpsecakmtqaazureweWindow4()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "https://eca-kmt-qa.azurewebsites.net/";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("https://eca-kmt-qa.azurewebsites.net/");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
    }
}
