//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ResourceId { get; set; }
        public string ApplicationName { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset RevisedOn { get; set; }
        public int RevisedBy { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
