//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.PermissionAssignments = new HashSet<PermissionAssignment>();
            this.RoleResourcePermissions = new HashSet<RoleResourcePermission>();
        }
    
        public int PermissionId { get; set; }
        public string PermissionName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ResourceTypeId { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public string PermissionDescription { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset RevisedOn { get; set; }
        public string RevisedBy { get; set; }
        public Nullable<int> ParentResourceTypeId { get; set; }
    
        public virtual Resource Resource { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual ICollection<PermissionAssignment> PermissionAssignments { get; set; }
        public virtual ICollection<RoleResourcePermission> RoleResourcePermissions { get; set; }
        public virtual ResourceType ParentResourceType { get; set; }
    }
}
