//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public Role()
        {
            this.PrincipleRoles = new HashSet<PrincipleRole>();
            this.RoleResourcePermissions = new HashSet<RoleResourcePermission>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTimeOffset RevisedOn { get; set; }
        public int RevisedBy { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ResourceId { get; set; }
        public Nullable<int> ResourceTypeId { get; set; }
    
        public virtual ICollection<PrincipleRole> PrincipleRoles { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual ResourceType ResourceType { get; set; }
        public virtual ICollection<RoleResourcePermission> RoleResourcePermissions { get; set; }
    }
}
