//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAM.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleResourcePermission
    {
        public int RoleId { get; set; }
        public int ResourceId { get; set; }
        public int PermissionId { get; set; }
        public System.DateTimeOffset AssignedOn { get; set; }
        public int AssignedBy { get; set; }
    
        public virtual Permission Permission { get; set; }
        public virtual Resource Resource { get; set; }
        public virtual Role Role { get; set; }
    }
}
