/* Removes erroneous ALL NULL rows following import from spreadsheet */

USE [VisitingScholar]
GO

DELETE FROM [dbo].[VisitingScholarData]
--SELECT * FROM [dbo].[VisitingScholarData]
      WHERE [Coop Agency]
           IS NULL AND [Category]
           IS NULL AND [Subcategory]
           IS NULL AND [Fiscal Year]
           IS NULL AND [Prefix]
           IS NULL AND [Last Name]
           IS NULL AND [First Name]
           IS NULL AND [Second Last Name]
           IS NULL AND [Middle Name]
           IS NULL AND [Suffix]
           IS NULL AND [Title]
           IS NULL AND [Position or Occupation Type]
           IS NULL AND [Ambassador]
           IS NULL AND [Disability]
           IS NULL AND [Home Emergency Email Address]
           IS NULL AND [Home Emergency Phone]
           IS NULL AND [Home Emergency Name]
           IS NULL AND [Host Emergency Email Address]
           IS NULL AND [Host Emergency Phone]
           IS NULL AND [Host Emergency Name]
           IS NULL AND [Gender ]
           IS NULL AND [Date of Birth]
           IS NULL AND [Birth City]
           IS NULL AND [Birth Country Name]
           IS NULL AND [Citizenship Country Name]
           IS NULL AND [Date of Naturalization]
           IS NULL AND [Marital Status]
           IS NULL AND [Dual Citizenship Country Name]
           IS NULL AND [Home Address 1]
           IS NULL AND [Home Address 2]
           IS NULL AND [Home Address 3]
           IS NULL AND [Home Address 4]
           IS NULL AND [Home City]
           IS NULL AND [Home State or Province]
           IS NULL AND [Home Zip or Postal Code]
           IS NULL AND [Home Country Name]
           IS NULL AND [Home Congressional District]
           IS NULL AND [Home Email]
           IS NULL AND [Home Phone]
           IS NULL AND [Home Fax]
           IS NULL AND [Host Address 1]
           IS NULL AND [Host Address 2]
           IS NULL AND [Host Address 3]
           IS NULL AND [Host Address 4]
           IS NULL AND [Host City]
           IS NULL AND [Host State or Province]
           IS NULL AND [Host Zip or Postal Code]
           IS NULL AND [Host Country Name]
           IS NULL AND [Host Congressional District]
           IS NULL AND [Host Email]
           IS NULL AND [Host Phone]
           IS NULL AND [Host Fax]
           IS NULL AND [Home Institution Name]
           IS NULL AND [Home Institution City]
           IS NULL AND [Home Institution State or Province]
           IS NULL AND [Home Institution Zip or Postal Code]
           IS NULL AND [Home Institution Country Name]
           IS NULL AND [Discipline]
           IS NULL AND [Area of Specialization]
           IS NULL AND [Activity Type Code]
           IS NULL AND [Activity Amendment Renewal]
           IS NULL AND [Activity Amendment Funded]
           IS NULL AND [Activity Amendment Extension]
           IS NULL AND [Funding Source Type]
           IS NULL AND [Host Institution Name]
           IS NULL AND [Host Institution City]
           IS NULL AND [Host Institution State or Province]
           IS NULL AND [Host Institution Zip or Postal Code]
           IS NULL AND [Host Institution Country Name]
           IS NULL AND [Institute Seminar Title]
           IS NULL AND [Institute Program Type]
           IS NULL AND [Grant Start Date]
           IS NULL AND [Grant End Date]
           IS NULL AND [Total Grant Amount]
           IS NULL AND [Program Type]
           IS NULL AND [Program Description]
           IS NULL AND [Degree Objective]
           IS NULL AND [Spouse Citizenship Country Name]
           IS NULL AND [Accompanying Dependent Num]
           IS NULL AND [Ethnicity]
           IS NULL AND [Race]
           IS NULL AND [SEVIS-ID]
           IS NULL AND [Exchange Visitor Category]
           IS NULL AND [Deceased]
           IS NULL AND [Project Number]
           IS NULL AND [Is Lecture]
           IS NULL AND [Is Seminar]
           IS NULL AND [Needs Assessment]
           IS NULL AND [Is Conference]
           IS NULL AND [Is Administrator Faculty Consult]
           IS NULL AND [Is Curriculum Development]
           IS NULL AND [Is Teacher Training]
           IS NULL AND [Is Other]
           IS NULL AND [Explanation]
           IS NULL AND [Record Is Valid] IS NULL
GO


